version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    # Remova o volume temporariamente para testar
    # volumes:
    #   - .:/app
    environment:
      - FLASK_ENV=development
